source "https://rubygems.org"

gem "kramdown"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"
gem "gemoji"
gem "csv"
gem "base64"
gem "bigdecimal"

gem "webrick", "~> 1.8"
