name: kripto.istanbul
title: kripto.istanbul | Bilgilenmeye Hazır Mısın? :fire: :fire: :rocket: :rocket:
description: Kripto paralar ve teknolojileri hakkında bilgilendirici haber ve içerik sitesi. :fire: :fire: :rocket: :rocket:Kripto para piyasaları hakkında son dakika haberleri ve whitepaper analizleri kripto.istanbul'da!
tags:
  - kripto
  - coin
  - kripto para
  - bitcoin
  - ethereum
show_hero: true
menu:
  - title: Ana Sayfa
    url: /
  - title: Yazılar
    url: /
  - title: Hakkımızda
    url: /about
  - title: İletişim
    url: /contact
email: kripto.istanbul@gmail.com
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
paginate: 12
